import AsyncStorage from '@react-native-async-storage/async-storage';
export const products=[
    {
        key:1,
        user:"user1",
      image: "https://picsum.photos/id/237/3500/2095",
      title: "Example Product A",
      price: 19.99,
      category: 'accessory',
      desc: "This is an example product description.",
      page:'w',
      quantity:1,
    },
    {
        key:2,
        user:"user1",
      image: "https://picsum.photos/id/238/3500/2096",
      title: "Example Product B",
      price: 10.99,
      category: 'food',
      desc: "This is another example product description.",
      page:'wc',
      quantity:5,
    },
    {
        key:3,        
        user:"user1",
      image: "https://picsum.photos/id/239/3500/2097",
      title: "Example Product C",
      price: 29.99,
      category: 'adopt',
      desc: "This is yet another example product description.",
      page:'wc',
      quantity:3,
    },
      {
        key:4,
        user:"user1",
        image: "https://picsum.photos/id/237/3500/2094",
        title: "Example Product D",
        price: 19.99,
        category: 'accessory',
        desc: "This is an example product description.",
        page:'w',
        quantity:2,
      },
      {
        key:5,
        user:"user1",
        image: "https://picsum.photos/id/238/3500/2085",
        title: "Example Product E",
        price: 10.99,
        category: 'food',
        desc: "This is another example product description.",
        page:'',
        quantity:1,
      },
      {
        key:6,
        user:"kamil",
        image: "https://picsum.photos/id/239/3500/2075",
        title: "Example Product F",
        price: 29.99,
        category: 'adopt',
        desc: "This is yet another example product description.",
        page:'wc',
        quantity:1,
      },

      {
        key: 7,
        user:"kamil",
        image: "https://picsum.photos/id/237/3500/2092",
        title: "Product 1",
        price: 10.0,
        category: 'adopt',
        desc: "This is yet another example product description.",
        page:'c',
        quantity:5,
      },
      {
        key: 8,
        user:"kamil",
        image: "https://picsum.photos/id/237/3500/2091",
        title: "Product 2",
        price: 20.0,
        category: 'adopt',        
        desc: "This is yet another example product description.",
        page:'',
        quantity:5,
      },
      {
        key: 9,
        user:"kamil",
        image: "https://picsum.photos/id/237/3500/295",
        title: "Product 3",
        price: 15.0,
        category: 'adopt',
        desc: "This is yet another example product description.",
        page:'w',
        quantity:4,
      },

  ];
  AsyncStorage.setItem('product', JSON.stringify(products));
  
  